### ISSUE TITLE
Railcraft track recipes suggestion

### ISSUE THREAD

**Issue by Freddo3000** [breakinblocks/nutsandbolts#102]
Hello, I'm quite a big fan of railcraft myself and one of the aspects I quite liked was it's different crafting system from vanilla where instead of just shoving iron ingots and sticks together, you actually had to make proper track beds using creosote oil and rails in rolling machines.

The railcraft version was also much more efficient than the current one, since for 6 iron you could get 8 pieces of rail, and six of those were enough for 32 bits of track, as opposed to 16 by using this recipe.

Now I don't necessarily suggest we switch back to the old railcraft system but I'd atleast appreciate having the option to make tracks that way, with the railcraft recipe existing aswell as the ingot based ones.

Thanks.

**Comment by Saereth** [comment]
This is a change from railcraft now us, I'm willing to double the output of the current recipe thouse just because rails are so rarely used, probably get to this over the weekend

**Comment by Freddo3000** [comment]
@Saereth 

I'm pretty sure there is a config option for whether or not to use custom recipes, would you please enable it?
