### ISSUE TITLE
Better Records radios non-functional

### ISSUE THREAD

**Issue by Freddo3000** [breakinblocks/nutsandbolts#103]
When trying to use a tuned frequency crystal, this message shown in the picture appears to all nearby players once inserted to a radio, and of course the radio simply doesn't play, Not sure if it is the same case with the Better Records record player.
![2016-01-27_20 15 22](https://cloud.githubusercontent.com/assets/14627848/12625206/10890f7c-c533-11e5-9541-3d4eb44a34df.png)

**Comment by Saereth** [comment]
That just means it couldnt connect to your stream, I was able to use different stream crystals. I forwarded this on to the dev but most likely just look for a better stream source.
