### ISSUE TITLE
Agricraft Ars Magica 2 Seed Combinations Missing

### ISSUE THREAD

**Issue by celainre** [breakinblocks/nutsandbolts#107]
The seed combinations for the Ars Magica 2 are missing/incorrect due to Cinderpearl Seeds not working correctly.  Currently the unattainable combinations are:

Cerublossom: Cinderpearl + Desert Nova
Aum: Cinderpearl + Cerublossom
Wakebloom: Cerublossom + Aum

**Comment by Saereth** [comment]
This is now fixed
