### ISSUE TITLE
Creative Energy Cell (AE2) Recipe Broken

### ISSUE THREAD

**Issue by celainre** [breakinblocks/nutsandbolts#117]
It appears that the assembly table recipe for the creative energy cell doesn't work.  It may have to do with the contents of the hohlraum, but If I recall correctly, Saereth said that it should be empty.

**Comment by Saereth** [comment]
It does actually need to be filled, representing the progress in the mek tech lines

**Comment by celainre** [comment]
Update: I have filled the hohlraum with D-T fuel.  The recipe still does not work.  I also tried it with both empty and fully charged dense energy cubes.
