### ISSUE TITLE
Random Things Spectre Key Room - Spawned with missing floor blocks.

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/nutsandbolts#124]
http://imgur.com/J7fij3Z

Not sure if it is only the first Spectre room at 0,0 that is created that is affected. Would need multiplayer to test more thoroughly.

**Comment by Saereth** [comment]
Lol rip, unfortunately thats a mod bug but not entirely game breaking so I'll report to the randomthings dev and leave this issue open for now, can you reproduce this or was a one time glitch?

**Comment by Sentrus** [comment]
Haven't been able to reproduce. Made three more worlds to test, each spawned a room correctly in that same location.
