### ISSUE TITLE
cannot craft tweaked mekanism/rftools machine frames

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#137]
On the server I just upgraded to NAB 3.6, the client has recipes for the RFTools Machine Frame and the Mekanism Steel Casing that, when I try to pull them out of the crafting grid, just bounce back and don't actually give me any result:

http://imgur.com/a/c9fj5

**Comment by Saereth** [comment]
This very much looks like a desync between the server and client scripts, can you zip the scripts on server and client seperately for me so I can investigate it further for you

**Comment by keturn** [comment]
https://www.dropbox.com/sh/0snu77jd10tav9z/AAAh07OW9POZcEkB6xLMW-Lua?dl=0

they look to be identical.

So maybe it is related to this MineTweaker error message I'm seeing on connect? From the client's `latest.log`:

> [10:57:14] [Client thread/INFO]: [CHAT] ERROR: Error executing MineTweakerRecipeMaker: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.lib.inventory.ComparableItemStackSafe id= 1769325754 hashCode= 330235904 toString= cofh.lib.inventory.ComparableItemStackSafe@1769325754{m:0, i:rocks.boltsandnuts.bbtweaks.items.ItemTarBall@1712700622, v:5039}; object #2 =class cofh.lib.inventory.ComparableItemStackSafe id= 284401825 hashCode= 330235904 toString= cofh.lib.inventory.ComparableItemStackSafe@284401825{m:0, i:rocks.boltsandnuts.bbtweaks.items.ItemTarBall@1712700622, v:5039}
> 
> hashCode() and/or equals() have inconsistent implementation
> Key set lost entries, now got 45 instead of 49. This can manifest itself as an apparent duplicate key.
> [10:57:14] [Client thread/INFO]: [CHAT] Welcome to BreakinBlocks - Nuts and Bolts!

**Comment by Saereth** [comment]
looks like thermal expansion has an update that fixes this, I'll package it up with a few other updates this weekend and push it to curse

**Comment by keturn** [comment]
I believe I have the new scripts.zip uploaded to both server and client.

Obvious typo: in Crafting.zs `8storageModuleItem` is probably meant to be `rftools:storageModuleItem`

but, once that's fixed, I still get the earlier message about tarballs,

and putting a Mek control circuit into the crafting grid still makes it _look like_ it'll turn into an IC2 circuit but that still doesn't work.

nor does this EnderIO chassis 

![2017-04-02_enderio-chassis](https://cloud.githubusercontent.com/assets/83819/24591994/01759864-17c3-11e7-8fcc-44aef5a4347a.jpg)

:disappointed:

**Comment by Saereth** [comment]
k I'll get this setup to finish testing locally, this happened when the mt files were segmented to mod specific files, there is a load/remove order discrepancy for some of the recipes. With a bit more time this week I should be able to get the remainders cleared up.

**Comment by keturn** [comment]
Based on that comment, I tried to arrange things so all the Removes are run first.

Assuming the scripts are sorted. Which I saw a comment somewhere that they are. But the minetweaker wiki says they are run in "no particular order." So who knows.

With these scripts on both server and client, I can make an RFTools Machine Frame and an EnderIO Chassis.

NEI shows **no** recipes for the Mekanism Steel Casing at all.

There were other seemingly-unrelated recipes I was having the "crafting grid shows result but can't pick it up" problem with earlier, like resourcefulcrops diamond seeds, that seems to have been resolved.
 
This isn't a pull request because the git repo doesn't match the structure of the scripts you gave me very well, but here's a zip of my scripts directory.

[best-scripts.zip](https://github.com/breakinblocks/nutsandbolts/files/908711/best-scripts.zip)

Oh, one more thing about that scripts directory: it has our server's local modifications that un-remove the non-Tinkers tools and undo their durability nerfs. As if the diff weren't sloppy enough already! But hopefully it's useful data.

**Comment by keturn** [comment]
Oh, and since I mentioned it earlier in this ticket. This organization of the scripts does not make the `Key set lost entries, now got 45 instead of 49` error message go away. (Which it wouldn't, if Thermal Expansion is the thing causing that.)

**Comment by keturn** [comment]
Further testing shows that minetweaker does, in fact, hate us, and will run scripts in whatever order strikes its fancy at the moment:

```
INFO: Z-2 Mek adds mek casing for Galacticraft, IC2, Railcraft
INFO: Z-2 Mek DONE added mek casing for Galacticraft, IC2, Railcraft
INFO: Crafting.zs adds mek casing
INFO: A-O Mek Removes mek casing
```

soooooo I guess if we split things into different files, all the adds/removes for a particular thing have to be in a single file, we can't have both Crafting.zs and the other files operate on the same things.

...

so then I thought, well, this is only a problem since we remove *all* the recipes for `Mekanism:BasicBlock:8`, if we targeted just the _one_ we want to remove, it wouldn't matter if it runs first or last.

Except that's a Mekanism Shaped Recipe, which Minetweaker appears to not have the methods to deal with. :imp:

**Comment by Saereth** [comment]
what you say here is right, all add/removes need to happen on a per file basis, I've been reoranizing all the files but havent quit finished it yet, its alot of recipes :P. 

if you want the easiest way, although it doesn't look great, you can move ALL scripts into a single file. all removes at the top, all additions in the bottom.

**Comment by keturn** [comment]
The thing that made me hesitant to mess with Crafting.zs is that it has the comments in it saying "generated file! do not mess with the markers!" etc. And it seems to get written when I join the server, which the other files do not.

Are we keeping any recipes in a generated file like this, or should everything get split out from that file entirely?

**Comment by Saereth** [comment]
crafting.zs is important for recipe maker, you could move everything to a general.zs and just do it all there, would work fine. For readability and troubleshooting you generally want them in seperate files, but segmenting them is what broke several recipes by some removes getting left behind in the move etc. 

To fix it I literally moved everything to general.zs and I'm going mod by mod separating them again. But just putting everything in general.zs and booting works.

**Comment by keturn** [comment]
If I had some time to spend on separating out things from Crafting.zs today, should I start from the copy I have, or the one in the repo, or is there one you've been working on?

**Comment by Saereth** [comment]
if you're already got a copy with changes you made then use that if you use mine its going to undo and mix up alot of the stuff you changed with tool durabiltiies etc

**Comment by keturn** [comment]
And when stuff gets split out of Crafting.zs, does it stay in `/scripts/MineTweakerRecipeMaker/scripts/`, or are those files more appropriate to place at the top-level `/scripts/` directory?

**Comment by Saereth** [comment]
doesnt matter, mt will check both spots, I kept them all in the MT/scripts folder since mt recreates it on launch anyway, allows you to keep all scripts in one folder that way
