### ISSUE TITLE
client crash following mystcraft teleport near TARDIS landing pad

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#140]
When I use a Mystcraft link-book to teleport into an area with a TARDIS landing pad nearby, the client crashes. Removing the landing pad blocks makes the crash go away.

(this crash was also present in nab 3.5.6)

```
-- Head --
Stacktrace:
        at tardis.common.tileents.ComponentTileEntity.func_145845_h(ComponentTileEntity.java:188)
        at tardis.common.tileents.LandingPadTileEntity.func_145845_h(LandingPadTileEntity.java:79)
        at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
        Name: tile.TardisMod.LandingPad // tardis.common.tileents.LandingPadTileEntity
        Block type: ID #3281 (tile.TardisMod.LandingPad // tardis.common.blocks.LandingPadBlock)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-347,100,-3824), Chunk: (at 5,6,0 in -22,-239; contains blocks -352,0,-3824 to -337,255,-3809), Region: (-1,-8; contains chunks -32,-256 to -1,-225, blocks -512,0,-4096 to -1,255,-3585)
        Actual block type: ID #3281 (tile.TardisMod.LandingPad // tardis.common.blocks.LandingPadBlock)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
```

Full crash report at https://gist.github.com/keturn/5a22e9d72b923e1aedddd483e611df68

**Comment by Saereth** [comment]
This is an issue with looking glass that never got resolved, using a portal frame for mystcraft to teleport to a tardis interior will fix this, or you can alternatively remove looking glass. I'm going to leave this issue open even though there isnt much I can do about this. I might just go ahead and remove looking glass in the next update.

**Comment by keturn** [comment]
Compact Machines gets all crashy when Looking Glass is enabled in its config too.

**Comment by Saereth** [comment]
yeah we'll go ahead and pull it, looking glass is nice but he hasnt worked on it in ages and doesnt seem like he will soon

**Comment by Saereth** [comment]
looking glass removed in next update
