### ISSUE TITLE
newly generated chunks are MooshroomIsland

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#141]
As I traveled into some previously-unexplored chunks in this server that was recently updated from the 3.5.6 version, I noticed the transition to the mooshroom biome was _much_ more abrupt than I'm used to seeing in RTG. 

[desert to river](http://i.imgur.com/FnVyotY.jpg)

But then as the mooshroom biome went on, and on, and on ...

[dynmap view](http://i.imgur.com/oRFwQJC.jpg)

I remembered something Plaxcale said the other day about seeing too much mooshroom biome.

My `server.properties` still has `level-type=RTG`, as it did when the world was initially generated.

I could double-check, because my version history of what happened to configs across the upgrade is still a little hard to read, but I _think_ the `biomesofplenty/biomegen.cfg` file is unchanged.

Sounds related: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/566

but the solution linked to there is along the lines of "disable mushrooms harder", which is different than what I was hearing in BB discord about mooshroom biome being a stand-in for a broken/not-found biome.

**Comment by PotDucky** [comment]
You can fix the Mushroom Biomes being everywhere by going to Config/biomesoplenty/biomegen.cfg , and changing the Ocean override to false (near bottom of config file):

"vanilla biomes to override"
    B:Ocean=false

**Comment by Saereth** [comment]
lol Potducky is correct, when bop updated the config got replaced with a defaulted one, I'll package the correct connfig in an update for this weekend.

**Comment by keturn** [comment]
Okay, I did the Ocean=false change in the section suggested above, and things are _less_ mushroomy now, but it's not yet clear to me whether things are working as intended. the borders between the 3.5.6-chunks and new-chunks are still _very_ sharp.

Also, after the biome allocation is fixed, is there a way to correct the chunks that got generated in the meantime? Either by admin command or in-game mechanisms. I've noticed that some of Reika's mods have various biome-altering tools.

**Comment by keturn** [comment]
that Ocean=false wasn't in the nab 3.5.6 server config

the only differences I see in the BoP configs are these, which don't seem relevant:

```.diff
diff -burN 3.5/config/biomesoplenty/misc.cfg 3.6/config/biomesoplenty/misc.cfg
--- 3.5/config/biomesoplenty/misc.cfg	2016-07-28 11:50:48.000000000 -0700
+++ 3.6/config/biomesoplenty/misc.cfg	2017-03-17 14:16:23.000000000 -0700
@@ -10,6 +10,7 @@
     B:"Add Custom Dungeon Loot"=false
     B:"Behave Normally During Special Events"=false
     B:"Enable Biomes O' Plenty Main Menu Panorama"=true
+    B:"Enable Poison Ivy Effects"=true
     B:"Enable Spring Water Regeneration Effect"=true
 }
 
diff -burN 3.5/config/biomesoplenty/terraingen.cfg 3.6/config/biomesoplenty/terraingen.cfg
--- 3.5/config/biomesoplenty/terraingen.cfg	2016-07-28 11:50:48.000000000 -0700
+++ 3.6/config/biomesoplenty/terraingen.cfg	2017-03-17 14:16:23.000000000 -0700
@@ -22,6 +22,9 @@
     B:genSapphireOre=false
     B:genTanzaniteOre=false
     B:genTopazOre=false
+
+    # Disable or Enable wasp hives in the Nether.
+    B:genWaspHives=true
 }
```

**Comment by Saereth** [comment]
we never had the mushroom biome issue with worldtype rtg, apparently the update of BOP does cause this now with rtg so the config just needs to be set to reflect that, you have the right change. As for regenerating those chunks... you can delete the region files effected and they'll regenerate. This would obviously nuke any building that had taken place in those region files

**Comment by keturn** [comment]
Okay, I did some more flying around, and it does look like new chunks have an appropriate distribution of biomes and terrain.

I can accept some rough edges between old-chunks and new-chunks as long as the world hasn't become squashed to one or two sorts of biomes.
