### ISSUE TITLE
Aura Cascade log spam (hundreds of kilobytes)

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#143]
Aura Cascade frequently puts out log entries like this:

```
363504[14:18:34] [GA-DataSendThread/INFO] [STDERR/]: [de.npe.gameanalytics.EventHandler$RESTHelper:sendData:209]: Failed to send analytics event data. Result of attempt: ok
```

Those log entries are often quite short, but I have others where a single line in the log file is _three hundred kilobytes_, which is entirely bonkers. (over two thousand events in that single "data sent" payload.)

I think when we did some research on this one, I found that the GameAnalytics library it uses has been updated to be less spammy; the version bundled in Aura Cascade's jar is now old.

[We've talked about this one on Discord, putting an issue here for tracking.]

**Comment by Saereth** [comment]
disable mcsnooper in the server properties

**Comment by keturn** [comment]
That was from the client log, but yes, the same advice (disable snooper) probably applies.

It's just a shame to disable analytics for everyone for the sake of a bug in one mod.

**Comment by Saereth** [comment]
short of doing a custom build of auracascade there isnt really another fix for it atm. Although I have done some custom builds of AC so if it may be something I'll revisit in the future.

**Comment by Saereth** [comment]
duplicate issue

**Comment by keturn** [comment]
Confirmed that these messages do _not_ show up in fml-client-latest.log when `snooperEnabled:false`. :+1:
