### ISSUE TITLE
NPE during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#144]
This isn't _quite_ the extenstial threat to disk space that the Aura Cascade analytics spam is, but it happens a lot and each of these stack traces is over 50 lines and 9 kB.

https://gist.github.com/keturn/ffe006e075eb036a10a220ddefcc34d7

**Comment by Saereth** [comment]
I may revisit to do a custom build of AC to fix this in the future but as 1.7.10 isnt greatly supported by most dev authors these days, im not certain when I'll get around to this. Closing for now as turning off snooper in the server.properties is a work around for this issue.

**Comment by keturn** [comment]
Okay, I'll see if I can reproduce this with snooper off, but I had been considering this ItemTooltipEvent error and the Aura Cascade GA thing as independent issues.

**Comment by keturn** [comment]
Confirmed that these messages do _not_ show up in fml-client-latest.log when `snooperEnabled:false`. :+1:
