### ISSUE TITLE
(NaB 3.5.6) AE2 Stuff Crash, Incorrect version included with pack.

### ISSUE THREAD

**Issue by PotDucky** [breakinblocks/nutsandbolts#146]
You're currently including ae2stuff-0.5.1.61-mc1.7.10.jar with the NaB1 modpack. This is incompatible with AE2 rv3. 

Downgrading to ae2stuff-rv3-0.5.1.9-mc1.7.10.jar fixes the issues.

**Comment by Saereth** [comment]
Fixed next update. I know Reiksa has been working on v17 so I was delaying an update until it's ready but if it goes another week I'll push out a an update to fix several minor outstanding issues, this included.
