### ISSUE TITLE
Rose Gold will not craft

### ISSUE THREAD

**Issue by Paasion** [breakinblocks/nutsandbolts#150]
Metal alloyer for atm rockhounding will not accept the silver dust to craft the rose gold.  It will accept the gold and copper dust however when adding the silver dust to complete the recipe, the alloyer will not accept it.  Play is stopped at this point until fixed.

**Comment by joral** [comment]
This issue is located in the wrong project.  This is for the original Nuts and Bolts pack on 1.7.10, which does not have ATM Rockhounding.  This should be logged in the nutsandbotstorqued project.

**Comment by Saereth** [comment]
cant reproduce this
