### ISSUE TITLE
Thermal expansion Creative energy cell not craftable

### ISSUE THREAD

**Issue by flashsugar** [breakinblocks/nutsandbolts#152]
creative energy cell cannot be crafted due to ae2 energy cell not having a recipe

[![https://gyazo.com/65e4640fabc1cf4be4d6eb9097f68350](https://i.gyazo.com/65e4640fabc1cf4be4d6eb9097f68350.png)](https://gyazo.com/65e4640fabc1cf4be4d6eb9097f68350)

**Comment by Saereth** [comment]
fixed
