### ISSUE TITLE
Mod Interaction issue between DragonAPI and Witchery

### ISSUE THREAD

**Issue by NiGHTM4R3** [breakinblocks/nutsandbolts#157]
The Client crashes because of a small issue with the tick-entities method, a problem which as seen here:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1538
Was already acknowledged and fixed by Reika in the newer versions of the mods however still present in the V17 of the mods that is being used in Nuts and Bolts, updating is not easily possible however for the people that are less skilled at editing modpacks since it brings up tons of issues starting with but not limited to ID conflicts on Biomes O Plenty and many more.
Removing those mods in conflict is not easily done either since it breaks a ton of scripts and recipes regarding the conflicting mods.
A professional update of the mods in question (reikas) would be appreciated if done by the Nuts and Bolts team instead of a hackjob that works more or less and is the result of just removing stuff entirely.

**Comment by m0nkm0nk** [comment]
@NiGHTM4R3 If you want can still provide you with latest files. Most 1.7.10 mods are final by now so updates are rare.
