### ISSUE TITLE
Osmotic Enchanter crash

### ISSUE THREAD

**Issue by Gerhardo93** [breakinblocks/nutsandbolts#158]
Using the Osmotic Enchanter (Thaumic Tinkerer) crashes the game client-side and deletes both the osmotic enchanter and any item in it from the world.

**Comment by Saereth** [comment]
got a crash log?

**Comment by Gerhardo93** [comment]
[crash-2019-11-11_18.14.44-client.txt](https://github.com/breakinblocks/nutsandbolts/files/3842011/crash-2019-11-11_18.14.44-client.txt)

**Comment by Saereth** [comment]
this is fixed in latest
