### ISSUE TITLE
Texture pack

### ISSUE THREAD

**Issue by Alexus13** [breakinblocks/nutsandbolts#159]
Hi!
When I install the Texture pack (tested on Soartex and Faithfull 32 modded) items and blocks from Botania mod do not accept new textures

**Comment by Saereth** [comment]
Edit your botania config and set this line to false, that should fix it for you.
https://github.com/breakinblocks/nutsandbolts/blob/1.7.10/config/Botania.cfg#L62

**Comment by Alexus13** [comment]
Thank you!!
