### ISSUE TITLE
Enabling Essence Seeds

### ISSUE THREAD

**Issue by weff47** [breakinblocks/nutsandbolts#61]
I would like to see a way to get essence seeds that is fairly balanced. In my opinion without a way to create essence besides mining, having magical crops in the modpack is pointless. By the time you create a way to easily mine a lot of essence dust from the ore, you might as well just use the mining method to get your resources instead.

I understand that enabling essence seeds can be fairly broken if not balanced correctly but I think it should be possible to find a way to balance it correctly. There are two options I can currently think of that may make it balanced enough. The first would be to make them craftable using a high tier essence gem like strong or extreme. This would mean that each seed needs 256 or 1024 essence dust to craft, enoough essence that warrants either a lot of mining or a small automated mining setup. The second option is to enable seed spawns from tall grass at a very low occurrence. This would limit the availability of early seeds but has the drawback of being able to make a setup to farm the seeds by making a tall grass farm.

Either way I think having essence seeds enabled in some way provides a way to feasibly be able to use the mod. This is my favorite mod and I would like to be able to play with it without spending a stupid amount of time on it. :)

**Comment by Saereth** [comment]
We're switching to resourceful crops so this is no longer a concern

**Comment by Saereth** [comment]
we will have a way to get seeds for resourcefulcrops
