### ISSUE TITLE
Reduce Dimensional Anchor Fuel Value

### ISSUE THREAD

**Issue by MajorclaM** [breakinblocks/nutsandbolts#65]
I propose that eyes of ender should not last six hours per eye. Having the potential for chunks to be loaded for 16 days is excessive imho. My recommendation is reducing the eye's fuel values to match ender pearls. The more expensive eyes are able to load for longer because of the increased stack size.

**Comment by Milkyway3640** [comment]
I agree, but, I'd like to talk with the others before charging ahead with config changes.

**Comment by Saereth** [comment]
make it take nether stars! 1 hour per star

**Comment by Milkyway3640** [comment]
Very Smooth Saereth, way to echo Carl.

I like the idea, offline chunkloading is rather expensive on the server, and for people that actively play and refresh the chunkloader often, it's not an issue. 16 days for someone that's left the server to expire is excessive, especially when the server has only been up for a little longer than that amount.

Maybe not reducing the eye's effectiveness, but dropping it as a fuel altogether, and changing it to something that doesnt stack as much.  Maybe DS could make a specal item via custom things that only stacks up to 8 or 16 and we can go from there? That would be pretty cool.

Alternatively, we could make it something from CustomNPCs only available from the admin shop. Something that would be guaranteed to get money out of the economy.  

We could also just make them harder in general, the ender eyes last for a few days, perfect for the player that plays frequently and is just starting out, and make the long term solution, say a week, for something more expensive, like eyes of galgador, which combine magma cream, one of the loading options, and eyes of ender, a previous option, with some other harder materials.

We could also make exploration alternatives, blue gem from pluto would be cool, or maybe ectoplasm from Random Things, fertile soil from atum, pez or jelly or whatever from candy craft, or maybe meteors from the moon, and venus blaze powder, we have a heck of a lot of options for this, and it would fit the theme of the pack perfectly.

**Comment by Saereth** [comment]
Resolved with breakbit system
