### ISSUE TITLE
Disconnected when using Mekanism Personal Teleporter

### ISSUE THREAD

**Issue by kesppr** [breakinblocks/nutsandbolts#68]
Whenever I right click with the Mekanism Personal Teleporter I get disconnected from the server (breakinblocks NaB) with an "Internal Server Error" message or sometimes a "[...] Disconnected by Peer", but only if the pitch of my head (vertical inclination measured with /getpos) is beyond certain values, which differ depending on the y-level I'm standing at. This is what I measured (y-level is feet y-level):
y = 2;     pitch < -70°
y = 39;   pitch < 21°
y = 72;   pitch < 21°
y = 115; pitch < ~48°
Wasn't able to reproduce in singleplayer. Was able to reproduce in different locations on the server.

**Comment by Saereth** [comment]
Fixed in new mekanism build
