### ISSUE TITLE
A few things, which I think are bugs, but may be intended

### ISSUE THREAD

**Issue by ReluctantSniper** [breakinblocks/nutsandbolts#96]
Hey all! Loving the modpack, but I've noticed a few things which I'm not sure are bugs or features, figured I'd ask!
The forestry mining backpack isn't picking anything up at all.
I can't craft a machine inventory manager from SFM. It acts as though the crafting recipe is disabled.
Also, I can't craft iron bars from vanilla MC, the recipe makes the big metal bar from OpenBlocks, which I think is their wrench.
I also think I'm getting reduced or no flint when mining gravel, even with fortune upgrades, but I assume this is intended since there is a recipe to turn 3 gravel into 1 flint.

**Comment by Saereth** [comment]
1. I will look into this, thats odd
2. .are you trying to craft the SFM in an AE terminal or vanilla table? 
3. probably a recipe conflict, I'll check
4. the flint is intended, its part of iguana tweaks, there are also ways to make flint

Also which version of the pack are you using?

**Comment by ReluctantSniper** [comment]
2: It's in a tinker's construct crafting table, but the recipe won't even show in NEI. Tried with a vanilla crafting table, no dice.

I am using version 3.0.p is what it shows in the splash screen, technic launcher shows 3.2.5

**Comment by Someweb** [comment]
Double check the current nab version in the technic launcher, the version on the splash is a little bit behind, I'm guessing if you have the latest version you're on 3.2.1 or 3.2.5

**Comment by ReluctantSniper** [comment]
Yeah it's shown as 3.2.5 in the technic launcher. Is this pack also on the ftb launcher? I'd much rather use that

**Comment by Saereth** [comment]
We are on FTB although a version behind, it takes them a good week to update for us on FTB when we post new patches. The new version coming out will be on FTB soon with the server files included. In the meantime I'm working on a small patch that should fix most of your issues. Should be done with it this evening.

**Comment by ReluctantSniper** [comment]
Awesome, thanks for the quick work!

**Comment by Saereth** [comment]
All of these issues have now been resolved in update 3.2.5a available on the technic launcher
